In [1]:
import polars as pl
import datetime
from polars import DataFrame

In [2]:
dataset = '../data/HI-Medium_Trans.csv'

trans = (
    pl.read_csv(dataset)
    .with_columns(
        pl.col("Timestamp").str.strptime(pl.Datetime, '%Y/%m/%d %H:%M', strict=True)
    )
    .sort('Timestamp')
)

In [3]:
trans.head()

shape: (5, 11)
┌────────────┬───────────┬───────────┬─────────┬───┬───────────┬───────────┬───────────┬───────────┐
│ Timestamp  ┆ From Bank ┆ From      ┆ To Bank ┆ … ┆ Amount    ┆ Payment   ┆ Payment   ┆ Is Launde │
│ ---        ┆ ---       ┆ ---       ┆ ---     ┆   ┆ Paid      ┆ Currency  ┆ Format    ┆ ring      │
│ datetime[μ ┆ i64       ┆ str       ┆ i64     ┆   ┆ ---       ┆ ---       ┆ ---       ┆ ---       │
│ s]         ┆           ┆           ┆         ┆   ┆ f64       ┆ str       ┆ str       ┆ i64       │
╞════════════╪═══════════╪═══════════╪═════════╪═══╪═══════════╪═══════════╪═══════════╪═══════════╡
│ 2022-09-01 ┆ 1046      ┆ 800A37D90 ┆ 274159  ┆ … ┆ 26.42     ┆ US Dollar ┆ Credit    ┆ 0         │
│ 00:00:00   ┆           ┆           ┆         ┆   ┆           ┆           ┆ Card      ┆           │
│ 2022-09-01 ┆ 21418     ┆ 800AB4DE0 ┆ 21418   ┆ … ┆ 23.61     ┆ US Dollar ┆ Reinvestm ┆ 0         │
│ 00:00:00   ┆           ┆           ┆         ┆   ┆           ┆           ┆ ent       ┆           │
│ 2022-09-01 ┆ 32248     ┆ 80056BBD0 ┆ 11      ┆ … ┆ 12373.74  ┆ US Dollar ┆ ACH       ┆ 0         │
│ 00:00:00   ┆           ┆           ┆         ┆   ┆           ┆           ┆           ┆           │
│ 2022-09-01 ┆ 11798     ┆ 80145BAF0 ┆ 11798   ┆ … ┆ 4981.27   ┆ US Dollar ┆ Reinvestm ┆ 0         │
│ 00:00:00   ┆           ┆           ┆         ┆   ┆           ┆           ┆ ent       ┆           │
│ 2022-09-01 ┆ 1924      ┆ 800CCE420 ┆ 1924    ┆ … ┆ 22.94     ┆ US Dollar ┆ Reinvestm ┆ 0         │
│ 00:00:00   ┆           ┆           ┆         ┆   ┆           ┆           ┆ ent       ┆           │
└────────────┴───────────┴───────────┴─────────┴───┴───────────┴───────────┴───────────┴───────────┘

In [4]:
zero = trans['Timestamp'].min()
hundred = trans['Timestamp'].max()

In [5]:
diff = hundred - zero
days = diff.days
sixty = zero + datetime.timedelta(days=days * 0.6)
eighty = zero + datetime.timedelta(days=days * 0.8)
hundred = zero + datetime.timedelta(days=days)

print(zero, sixty, eighty, hundred)

2022-09-01 00:00:00 2022-09-17 04:48:00 2022-09-22 14:24:00 2022-09-28 00:00:00

# Transform accounts to IDs

In [6]:
nodes = (
    trans
    .select(pl.col('From').alias('Acc'))
    .vstack(trans.select(pl.col('To').alias('Acc')))
    .unique()
    .with_row_index('Node ID')
)

ssl = (
    trans.join(nodes, left_on='From', right_on='Acc')
    .join(nodes, left_on='To', right_on='Acc', suffix='_to')
    .drop('From', 'To')
    .rename({
        'Node ID': 'From',
        'Node ID_to': 'To',
    })
)

In [11]:
ssl.head()

shape: (5, 11)
┌─────────────┬───────────┬─────────┬────────────┬───┬────────────┬────────────┬─────────┬─────────┐
│ Timestamp   ┆ From Bank ┆ To Bank ┆ Amount     ┆ … ┆ Payment    ┆ Is         ┆ From    ┆ To      │
│ ---         ┆ ---       ┆ ---     ┆ Received   ┆   ┆ Format     ┆ Laundering ┆ ---     ┆ ---     │
│ datetime[μs ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ ---        ┆ u32     ┆ u32     │
│ ]           ┆           ┆         ┆ f64        ┆   ┆ str        ┆ i64        ┆         ┆         │
╞═════════════╪═══════════╪═════════╪════════════╪═══╪════════════╪════════════╪═════════╪═════════╡
│ 2022-09-01  ┆ 1046      ┆ 274159  ┆ 26.42      ┆ … ┆ Credit     ┆ 0          ┆ 950276  ┆ 1143989 │
│ 00:00:00    ┆           ┆         ┆            ┆   ┆ Card       ┆            ┆         ┆         │
│ 2022-09-01  ┆ 21418     ┆ 21418   ┆ 23.61      ┆ … ┆ Reinvestme ┆ 0          ┆ 1311770 ┆ 1311770 │
│ 00:00:00    ┆           ┆         ┆            ┆   ┆ nt         ┆            ┆         ┆         │
│ 2022-09-01  ┆ 32248     ┆ 11      ┆ 12373.74   ┆ … ┆ ACH        ┆ 0          ┆ 1820335 ┆ 1575420 │
│ 00:00:00    ┆           ┆         ┆            ┆   ┆            ┆            ┆         ┆         │
│ 2022-09-01  ┆ 11798     ┆ 11798   ┆ 4981.27    ┆ … ┆ Reinvestme ┆ 0          ┆ 1214029 ┆ 1214029 │
│ 00:00:00    ┆           ┆         ┆            ┆   ┆ nt         ┆            ┆         ┆         │
│ 2022-09-01  ┆ 1924      ┆ 1924    ┆ 22.94      ┆ … ┆ Reinvestme ┆ 0          ┆ 1894020 ┆ 1894020 │
│ 00:00:00    ┆           ┆         ┆            ┆   ┆ nt         ┆            ┆         ┆         │
└─────────────┴───────────┴─────────┴────────────┴───┴────────────┴────────────┴─────────┴─────────┘

In [38]:
print(f"Number of unique nodes: {nodes.count()}")

Number of unique nodes: shape: (1, 2)
┌─────────┬─────────┐
│ Node ID ┆ Acc     │
│ ---     ┆ ---     │
│ u32     ┆ u32     │
╞═════════╪═════════╡
│ 2076999 ┆ 2076999 │
└─────────┴─────────┘

# Global vars

In [12]:
every = '2d'

In [13]:
def _prep(df: pl.DataFrame) -> pl.LazyFrame:
    return (
        df.lazy()
        .with_columns(
            pl.col('Timestamp').dt.truncate(every).alias("window_start")
        )
        .filter(
             pl.col('Timestamp').is_not_null()
             & pl.col('From').is_not_null()
             & pl.col('To').is_not_null()
        )
    )

In [14]:
_prep(ssl).collect()

shape: (31_898_238, 12)
┌─────────────┬───────────┬─────────┬────────────┬───┬────────────┬─────────┬─────────┬────────────┐
│ Timestamp   ┆ From Bank ┆ To Bank ┆ Amount     ┆ … ┆ Is         ┆ From    ┆ To      ┆ window_sta │
│ ---         ┆ ---       ┆ ---     ┆ Received   ┆   ┆ Laundering ┆ ---     ┆ ---     ┆ rt         │
│ datetime[μs ┆ i64       ┆ i64     ┆ ---        ┆   ┆ ---        ┆ u32     ┆ u32     ┆ ---        │
│ ]           ┆           ┆         ┆ f64        ┆   ┆ i64        ┆         ┆         ┆ datetime[μ │
│             ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ s]         │
╞═════════════╪═══════════╪═════════╪════════════╪═══╪════════════╪═════════╪═════════╪════════════╡
│ 2022-09-01  ┆ 1046      ┆ 274159  ┆ 26.42      ┆ … ┆ 0          ┆ 950276  ┆ 1143989 ┆ 2022-09-01 │
│ 00:00:00    ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ 00:00:00   │
│ 2022-09-01  ┆ 21418     ┆ 21418   ┆ 23.61      ┆ … ┆ 0          ┆ 1311770 ┆ 1311770 ┆ 2022-09-01 │
│ 00:00:00    ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ 00:00:00   │
│ 2022-09-01  ┆ 32248     ┆ 11      ┆ 12373.74   ┆ … ┆ 0          ┆ 1820335 ┆ 1575420 ┆ 2022-09-01 │
│ 00:00:00    ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ 00:00:00   │
│ 2022-09-01  ┆ 11798     ┆ 11798   ┆ 4981.27    ┆ … ┆ 0          ┆ 1214029 ┆ 1214029 ┆ 2022-09-01 │
│ 00:00:00    ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ 00:00:00   │
│ 2022-09-01  ┆ 1924      ┆ 1924    ┆ 22.94      ┆ … ┆ 0          ┆ 1894020 ┆ 1894020 ┆ 2022-09-01 │
│ 00:00:00    ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ 00:00:00   │
│ …           ┆ …         ┆ …       ┆ …          ┆ … ┆ …          ┆ …       ┆ …       ┆ …          │
│ 2022-09-28  ┆ 211767    ┆ 219853  ┆ 7339.28    ┆ … ┆ 1          ┆ 1538965 ┆ 2054979 ┆ 2022-09-27 │
│ 11:59:00    ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ 00:00:00   │
│ 2022-09-28  ┆ 211767    ┆ 211767  ┆ 5869.16    ┆ … ┆ 0          ┆ 1538965 ┆ 1538965 ┆ 2022-09-27 │
│ 12:14:00    ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ 00:00:00   │
│ 2022-09-28  ┆ 211767    ┆ 130596  ┆ 5869.16    ┆ … ┆ 1          ┆ 1538965 ┆ 209851  ┆ 2022-09-27 │
│ 12:14:00    ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ 00:00:00   │
│ 2022-09-28  ┆ 211767    ┆ 211767  ┆ 9257.95    ┆ … ┆ 0          ┆ 1538965 ┆ 1538965 ┆ 2022-09-27 │
│ 15:58:00    ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ 00:00:00   │
│ 2022-09-28  ┆ 211767    ┆ 16098   ┆ 9257.95    ┆ … ┆ 1          ┆ 1538965 ┆ 1014805 ┆ 2022-09-27 │
│ 15:58:00    ┆           ┆         ┆            ┆   ┆            ┆         ┆         ┆ 00:00:00   │
└─────────────┴───────────┴─────────┴────────────┴───┴────────────┴─────────┴─────────┴────────────┘

# Temporal stats

In [39]:
def add_temporal_stats(df: pl.DataFrame) -> pl.DataFrame:
    df = _prep(df).select(
        pl.col('window_start'),
        pl.col('Timestamp'),
        pl.col('From'),
        pl.col('To'),
    )

    in_gaps = (
        df.sort(["window_start", "To", "Timestamp"])
        .group_by(["window_start", "To"])
        .agg(
            pl.col('Timestamp').diff().dt.total_seconds().alias('gap')
        )
        .with_columns(
            pl.col("gap").list.drop_nulls().alias("gap")
        )
        .with_columns([
            pl.col("gap").list.mean().alias("mu_gap_in_sec"),
            pl.col("gap").list.var().alias("var_gap_in_sec"),
        ])
        .select(["window_start", 'To', "mu_gap_in_sec", "var_gap_in_sec"])
        .rename({'To': 'Node'})
    )

    out_gaps = (
        df.sort(["window_start", "From", "Timestamp"])
        .group_by(["window_start", "From"])
        .agg(
            pl.col('Timestamp').diff().dt.total_seconds().alias('gap')
        )
        .with_columns(
            pl.col("gap").list.drop_nulls().alias("gap")
        )
        .with_columns([
            pl.col("gap").list.mean().alias("mu_gap_out_sec"),
            pl.col("gap").list.var().alias("var_gap_out_sec"),
        ])
        .select(["window_start", 'From', "mu_gap_out_sec", "var_gap_out_sec"])
        .rename({'From': 'Node'})
    )

    return (
        in_gaps.join(out_gaps, on=["Node", 'window_start'], how="full", coalesce=True)
        .collect()
    )

In [40]:
temporal_features = add_temporal_stats(ssl)

In [41]:
temporal_features

shape: (9_337_964, 6)
┌──────────────┬─────────┬───────────────┬────────────────┬────────────────┬─────────────────┐
│ window_start ┆ Node    ┆ mu_gap_in_sec ┆ var_gap_in_sec ┆ mu_gap_out_sec ┆ var_gap_out_sec │
│ ---          ┆ ---     ┆ ---           ┆ ---            ┆ ---            ┆ ---             │
│ datetime[μs] ┆ u32     ┆ f64           ┆ f64            ┆ f64            ┆ f64             │
╞══════════════╪═════════╪═══════════════╪════════════════╪════════════════╪═════════════════╡
│ 2022-09-15   ┆ 1486638 ┆ null          ┆ null           ┆ null           ┆ null            │
│ 00:00:00     ┆         ┆               ┆                ┆                ┆                 │
│ 2022-09-13   ┆ 668634  ┆ 22440.0       ┆ 1.4725e9       ┆ null           ┆ null            │
│ 00:00:00     ┆         ┆               ┆                ┆                ┆                 │
│ 2022-09-01   ┆ 290756  ┆ 24342.857143  ┆ 1.9297e9       ┆ 54300.0        ┆ null            │
│ 00:00:00     ┆         ┆               ┆                ┆                ┆                 │
│ 2022-09-11   ┆ 1079620 ┆ 25752.0       ┆ 3.1147e9       ┆ null           ┆ null            │
│ 00:00:00     ┆         ┆               ┆                ┆                ┆                 │
│ 2022-09-11   ┆ 821487  ┆ 180.0         ┆ null           ┆ 6333.333333    ┆ 3.2523e8        │
│ 00:00:00     ┆         ┆               ┆                ┆                ┆                 │
│ …            ┆ …       ┆ …             ┆ …              ┆ …              ┆ …               │
│ 2022-09-15   ┆ 1530147 ┆ null          ┆ null           ┆ 21248.571429   ┆ 3.3527e8        │
│ 00:00:00     ┆         ┆               ┆                ┆                ┆                 │
│ 2022-09-13   ┆ 1073502 ┆ null          ┆ null           ┆ null           ┆ null            │
│ 00:00:00     ┆         ┆               ┆                ┆                ┆                 │
│ 2022-09-05   ┆ 1408649 ┆ null          ┆ null           ┆ 29260.0        ┆ 2.3069e9        │
│ 00:00:00     ┆         ┆               ┆                ┆                ┆                 │
│ 2022-09-15   ┆ 1395042 ┆ null          ┆ null           ┆ null           ┆ null            │
│ 00:00:00     ┆         ┆               ┆                ┆                ┆                 │
│ 2022-09-09   ┆ 1308043 ┆ null          ┆ null           ┆ null           ┆ null            │
│ 00:00:00     ┆         ┆               ┆                ┆                ┆                 │
└──────────────┴─────────┴───────────────┴────────────────┴────────────────┴─────────────────┘

# Fraudulent patterns

## 2-cycles

In [46]:
def count_reciprocal_neighbours(df: DataFrame) -> DataFrame:
    lf = _prep(df)

    edges = lf.select(["window_start", "From", "To"]).unique().filter(pl.col("From") != pl.col("To"))

    recip = (
        edges.join(
            edges,
            how="inner",
            left_on=["window_start", "From", "To"],
            right_on=["window_start", "To", "From"],
        )
        .select(["window_start", "From", "To"])
        .unique()
        .group_by(["window_start", "From"])
        .agg(
            pl.col("To").n_unique().alias("r_2cycle")
        )
        .rename({"From": "Node"})
    )

    nodes = (
        pl.concat([
            lf.select(["window_start", pl.col("From").alias("Node")]),
            lf.select(["window_start", pl.col("To").alias("Node")]),
        ])
        .unique()
    )

    return (
        nodes.join(recip, on=["window_start", "Node"], how="left")
        .with_columns(
            pl.col("r_2cycle").fill_null(0).cast(pl.Int64)
        )
        .collect()
    )

In [47]:
two_cycles = count_reciprocal_neighbours(ssl)

In [48]:
two_cycles

shape: (9_337_964, 3)
┌─────────────────────┬─────────┬──────────┐
│ window_start        ┆ Node    ┆ r_2cycle │
│ ---                 ┆ ---     ┆ ---      │
│ datetime[μs]        ┆ u32     ┆ i64      │
╞═════════════════════╪═════════╪══════════╡
│ 2022-09-01 00:00:00 ┆ 1863431 ┆ 0        │
│ 2022-09-01 00:00:00 ┆ 1150128 ┆ 0        │
│ 2022-09-07 00:00:00 ┆ 516338  ┆ 0        │
│ 2022-09-05 00:00:00 ┆ 1726037 ┆ 0        │
│ 2022-09-15 00:00:00 ┆ 998716  ┆ 0        │
│ …                   ┆ …       ┆ …        │
│ 2022-09-01 00:00:00 ┆ 1725707 ┆ 0        │
│ 2022-09-15 00:00:00 ┆ 381566  ┆ 0        │
│ 2022-09-11 00:00:00 ┆ 987511  ┆ 0        │
│ 2022-09-15 00:00:00 ┆ 612834  ┆ 0        │
│ 2022-09-09 00:00:00 ┆ 1507040 ┆ 0        │
└─────────────────────┴─────────┴──────────┘

In [49]:
two_cycles.describe()

shape: (9, 4)
┌────────────┬────────────────────────────┬───────────────┬────────────┐
│ statistic  ┆ window_start               ┆ Node          ┆ r_2cycle   │
│ ---        ┆ ---                        ┆ ---           ┆ ---        │
│ str        ┆ str                        ┆ f64           ┆ f64        │
╞════════════╪════════════════════════════╪═══════════════╪════════════╡
│ count      ┆ 9337964                    ┆ 9.337964e6    ┆ 9.337964e6 │
│ null_count ┆ 0                          ┆ 0.0           ┆ 0.0        │
│ mean       ┆ 2022-09-07 18:20:54.673845 ┆ 1.0387e6      ┆ 0.001221   │
│ std        ┆ null                       ┆ 599722.740056 ┆ 0.035827   │
│ min        ┆ 2022-09-01 00:00:00        ┆ 0.0           ┆ 0.0        │
│ 25%        ┆ 2022-09-03 00:00:00        ┆ 519187.0      ┆ 0.0        │
│ 50%        ┆ 2022-09-09 00:00:00        ┆ 1.038889e6    ┆ 0.0        │
│ 75%        ┆ 2022-09-13 00:00:00        ┆ 1.558066e6    ┆ 0.0        │
│ max        ┆ 2022-09-27 00:00:00        ┆ 2.076998e6    ┆ 3.0        │
└────────────┴────────────────────────────┴───────────────┴────────────┘

## Ego profile

In [50]:
EPS = 1e-12

def compute_ego_profiles(trans: DataFrame) -> DataFrame:
    lf = _prep(trans)

    out_stats = (
        lf.group_by(["window_start", "From"])
        .agg(
            pl.len().alias("deg_out"),
            pl.col("To").n_unique().alias("fan_out"),
            pl.col("Amount Paid").sum().alias("vol_out"),
        )
        .rename({"From": "Node"})
    )

    in_stats = (
        lf.group_by(["window_start", "To"])
        .agg(
            pl.len().alias("deg_in"),
            pl.col("From").n_unique().alias("fan_in"),
            pl.col("Amount Received").sum().alias("vol_in"),
        )
        .rename({"To": "Node"})
    )

    ego = (
        out_stats.join(in_stats, on=["window_start", "Node"], how="full")
        .with_columns(
            pl.col("deg_out").fill_null(0).cast(pl.Int64),
            pl.col("fan_out").fill_null(0).cast(pl.Int64),
            pl.col("vol_out").fill_null(0.0),
            pl.col("deg_in").fill_null(0).cast(pl.Int64),
            pl.col("fan_in").fill_null(0).cast(pl.Int64),
            pl.col("vol_in").fill_null(0.0),
        )
        .with_columns(
            ((pl.col("vol_in") - pl.col("vol_out"))/ (pl.col("vol_in") + pl.col("vol_out") + pl.lit(EPS))).alias("flow_imbalance")
        )
        .with_columns(
            pl.when(pl.col('window_start').is_null()).then(pl.col('window_start_right')).otherwise(pl.col('window_start')).alias('window_start'),
            pl.when(pl.col('Node').is_null()).then(pl.col('Node_right')).otherwise(pl.col('Node')).alias('Node'),
        )
        .drop('Node_right', 'window_start_right')
    )

    per_cur_in = (
        lf.group_by(["window_start", "To", "Receiving Currency"])
        .agg(pl.col("Amount Received").sum().alias("vol_in_cur"))
        .rename({"To": "Node", "Receiving Currency": "currency"})
    )

    mix_in = (
        per_cur_in.join(
            per_cur_in.group_by(["window_start", "Node"])
            .agg(pl.col("vol_in_cur").sum().alias("vol_in_sum")),
            on=["window_start", "Node"],
        )
        .with_columns((pl.col("vol_in_cur") / (pl.col("vol_in_sum") + pl.lit(EPS))).alias("p"))
        .group_by(["window_start", "Node"])
        .agg([
            pl.len().alias("n_currencies_in"),
            (-pl.col("p") * (pl.col("p") + pl.lit(EPS)).log()).sum().alias("currency_entropy_in"),
            pl.col("p").max().alias("top_currency_share_in"),
        ])
    )

    per_cur_out = (
        lf.group_by(["window_start", "From", "Payment Currency"])
        .agg(pl.col("Amount Paid").sum().alias("vol_out_cur"))
        .rename({"From": "Node", "Payment Currency": "currency"})
    )

    mix_out = (
        per_cur_out.join(
            per_cur_out.group_by(["window_start", "Node"])
            .agg(pl.col("vol_out_cur").sum().alias("vol_out_sum")),
            on=["window_start", "Node"],
        )
        .with_columns((pl.col("vol_out_cur") / (pl.col("vol_out_sum") + pl.lit(EPS))).alias("p"))
        .group_by(["window_start", "Node"])
        .agg([
            pl.len().alias("n_currencies_out"),
            (-pl.col("p") * (pl.col("p") + pl.lit(EPS)).log()).sum().alias("currency_entropy_out"),
            pl.col("p").max().alias("top_currency_share_out"),
        ])
    )

    full = (
        ego.join(mix_in, on=["window_start", "Node"], how="left")
        .join(mix_out, on=["window_start", "Node"], how="left")
        .with_columns(
            pl.col("n_currencies_in").fill_null(0).cast(pl.Int64),
            pl.col("currency_entropy_in").fill_null(0.0),
            pl.col("top_currency_share_in").fill_null(0.0),

            pl.col("n_currencies_out").fill_null(0).cast(pl.Int64),
            pl.col("currency_entropy_out").fill_null(0.0),
            pl.col("top_currency_share_out").fill_null(0.0),
        )
    )

    return full.collect()

In [53]:
ego_profile = compute_ego_profiles(ssl)

In [54]:
ego_profile

shape: (9_337_964, 15)
┌────────────┬─────────┬─────────┬─────────┬───┬────────────┬────────────┬────────────┬────────────┐
│ window_sta ┆ Node    ┆ deg_out ┆ fan_out ┆ … ┆ top_curren ┆ n_currenci ┆ currency_e ┆ top_curren │
│ rt         ┆ ---     ┆ ---     ┆ ---     ┆   ┆ cy_share_i ┆ es_out     ┆ ntropy_out ┆ cy_share_o │
│ ---        ┆ u32     ┆ i64     ┆ i64     ┆   ┆ n          ┆ ---        ┆ ---        ┆ ut         │
│ datetime[μ ┆         ┆         ┆         ┆   ┆ ---        ┆ i64        ┆ f64        ┆ ---        │
│ s]         ┆         ┆         ┆         ┆   ┆ f64        ┆            ┆            ┆ f64        │
╞════════════╪═════════╪═════════╪═════════╪═══╪════════════╪════════════╪════════════╪════════════╡
│ 2022-09-09 ┆ 2004072 ┆ 0       ┆ 0       ┆ … ┆ 1.0        ┆ 0          ┆ 0.0        ┆ 0.0        │
│ 00:00:00   ┆         ┆         ┆         ┆   ┆            ┆            ┆            ┆            │
│ 2022-09-11 ┆ 869769  ┆ 0       ┆ 0       ┆ … ┆ 1.0        ┆ 0          ┆ 0.0        ┆ 0.0        │
│ 00:00:00   ┆         ┆         ┆         ┆   ┆            ┆            ┆            ┆            │
│ 2022-09-13 ┆ 1969402 ┆ 4       ┆ 1       ┆ … ┆ 1.0        ┆ 1          ┆ -9.9920e-1 ┆ 1.0        │
│ 00:00:00   ┆         ┆         ┆         ┆   ┆            ┆            ┆ 3          ┆            │
│ 2022-09-11 ┆ 984491  ┆ 0       ┆ 0       ┆ … ┆ 1.0        ┆ 0          ┆ 0.0        ┆ 0.0        │
│ 00:00:00   ┆         ┆         ┆         ┆   ┆            ┆            ┆            ┆            │
│ 2022-09-13 ┆ 354060  ┆ 0       ┆ 0       ┆ … ┆ 1.0        ┆ 0          ┆ 0.0        ┆ 0.0        │
│ 00:00:00   ┆         ┆         ┆         ┆   ┆            ┆            ┆            ┆            │
│ …          ┆ …       ┆ …       ┆ …       ┆ … ┆ …          ┆ …          ┆ …          ┆ …          │
│ 2022-09-15 ┆ 538406  ┆ 1       ┆ 1       ┆ … ┆ 0.0        ┆ 1          ┆ -9.9742e-1 ┆ 1.0        │
│ 00:00:00   ┆         ┆         ┆         ┆   ┆            ┆            ┆ 3          ┆            │
│ 2022-09-15 ┆ 1060131 ┆ 10      ┆ 2       ┆ … ┆ 0.0        ┆ 1          ┆ -9.5035e-1 ┆ 1.0        │
│ 00:00:00   ┆         ┆         ┆         ┆   ┆            ┆            ┆ 3          ┆            │
│ 2022-09-15 ┆ 719593  ┆ 1       ┆ 1       ┆ … ┆ 0.0        ┆ 1          ┆ -9.9409e-1 ┆ 1.0        │
│ 00:00:00   ┆         ┆         ┆         ┆   ┆            ┆            ┆ 3          ┆            │
│ 2022-09-11 ┆ 1041540 ┆ 4       ┆ 1       ┆ … ┆ 0.0        ┆ 1          ┆ -9.9876e-1 ┆ 1.0        │
│ 00:00:00   ┆         ┆         ┆         ┆   ┆            ┆            ┆ 3          ┆            │
│ 2022-09-11 ┆ 1142888 ┆ 1       ┆ 1       ┆ … ┆ 0.0        ┆ 1          ┆ -9.9964e-1 ┆ 1.0        │
│ 00:00:00   ┆         ┆         ┆         ┆   ┆            ┆            ┆ 3          ┆            │
└────────────┴─────────┴─────────┴─────────┴───┴────────────┴────────────┴────────────┴────────────┘

# Flow-aware positional prediction

In [20]:
EPS = 1e-12

def flow_targets_out_entropy_count(trans: DataFrame, k2: bool = True) -> DataFrame:
    lf = _prep(trans).select(["window_start", "From", "To"])

    # Edge weight = count of transactions (currency invariant)
    W = (
        lf.group_by(["window_start", "From", "To"])
        .agg(pl.len().alias("w"))
    )

    out_sum = (
        W.group_by(["window_start", "From"])
        .agg(pl.col("w").sum().alias("out_wsum"))
    )

    P = (
        W.join(out_sum, on=["window_start", "From"], how="left")
        .with_columns((pl.col("w") / (pl.col("out_wsum") + pl.lit(EPS))).alias("p"))
        .select(["window_start", "From", "To", "p"])
    )

    one = (
        P.group_by(["window_start", "From"])
        .agg(
            (-pl.col("p") * (pl.col("p") + pl.lit(EPS)).log()).sum().alias("H_out_1_cnt"),
            pl.len().alias("supp_out_1_cnt"),
            pl.col("p").max().alias("pmax_out_1_cnt"),
        )
        .rename({"From": "Node"})
    )

    if not k2:
        return one.collect()

    # 2-step distribution via mid join: sum_mid P(src->mid)*P(mid->dst)
    P1 = P.rename({"From": "src", "To": "mid", "p": "p1"})
    P2 = P.rename({"From": "mid", "To": "dst", "p": "p2"})

    two_step = (
        P1.join(P2, on=["window_start", "mid"], how="inner")
        .with_columns((pl.col("p1") * pl.col("p2")).alias("p2step"))
        .group_by(["window_start", "src", "dst"])
        .agg(pl.col("p2step").sum().alias("p"))
    )

    two = (
        two_step.group_by(["window_start", "src"])
        .agg(
            (-pl.col("p") * (pl.col("p") + pl.lit(EPS)).log()).sum().alias("H_out_2_cnt"),
            pl.len().alias("supp_out_2_cnt"),
            pl.col("p").max().alias("pmax_out_2_cnt"),
        )
        .rename({"src": "Node"})
    )

    return one.join(two, on=["window_start", "Node"], how="left").collect()


def currency_mix_out(trans: DataFrame) -> DataFrame:
    lf = _prep(trans).select(["window_start", "From", "Payment Currency", "Amount Paid"])

    per_cur = (
        lf.group_by(["window_start", "From", "Payment Currency"])
        .agg(pl.col("Amount Paid").sum().alias("vol_out_cur"))
        .rename({"From": "Node", "Payment Currency": "currency"})
    )

    mix = (
        per_cur.join(
            per_cur.group_by(["window_start", "Node"])
            .agg(pl.col("vol_out_cur").sum().alias("vol_out_sum")),
            on=["window_start", "Node"],
        )
        .with_columns((pl.col("vol_out_cur") / (pl.col("vol_out_sum") + pl.lit(EPS))).alias("p"))
        .group_by(["window_start", "Node"])
        .agg([
            pl.count().alias("n_currencies_out"),
            (-pl.col("p") * (pl.col("p") + pl.lit(EPS)).log()).sum().alias("currency_entropy_out"),
            pl.col("p").max().alias("top_currency_share_out"),
        ])
    )

    return mix.collect()


def flow_heads_A_B(trans: DataFrame, k2: bool = True) -> DataFrame:
    head_a = flow_targets_out_entropy_count(trans, k2=k2)   # (window_start, node, ...)
    head_b = currency_mix_out(trans)                        # (window_start, node, ...)

    # Node universe: all active nodes in the window (senders or receivers)
    lf = _prep(trans).select(["window_start", "From", "To"])
    nodes = (
        pl.concat([
            lf.select(["window_start", pl.col("From").alias("Node")]),
            lf.select(["window_start", pl.col("To").alias("Node")]),
        ])
        .unique()
        .collect()
    )

    full = (
        nodes.lazy()
        .join(head_a.lazy(), on=["window_start", "Node"], how="left")
        .join(head_b.lazy(), on=["window_start", "Node"], how="left")
        .with_columns(
            # Fill missing: nodes with no outgoing edges => no flow / no currency mix
            pl.col("H_out_1_cnt").fill_null(0.0),
            pl.col("supp_out_1_cnt").fill_null(0).cast(pl.Int64),
            pl.col("pmax_out_1_cnt").fill_null(0.0),

            pl.col("H_out_2_cnt").fill_null(0.0),
            pl.col("supp_out_2_cnt").fill_null(0).cast(pl.Int64),
            pl.col("pmax_out_2_cnt").fill_null(0.0),

            pl.col("n_currencies_out").fill_null(0).cast(pl.Int64),
            pl.col("currency_entropy_out").fill_null(0.0),
            pl.col("top_currency_share_out").fill_null(0.0),
        )
        .collect()
    )

    return full

In [ ]:
train_pos_pred = flow_heads_A_B(ssl)

# Join

In [57]:
final = (
    temporal_features
    # .join(train_pos_pred, on=["window_start", "Node"], how="full", coalesce=True)
    .join(ego_profile, on=["window_start", "Node"], how="full", coalesce=True)
    .join(two_cycles, on=["window_start", "Node"], how="full", coalesce=True)
)

In [58]:
final

shape: (9_337_964, 20)
┌────────────┬─────────┬────────────┬───────────┬───┬───────────┬───────────┬───────────┬──────────┐
│ window_sta ┆ Node    ┆ mu_gap_in_ ┆ var_gap_i ┆ … ┆ n_currenc ┆ currency_ ┆ top_curre ┆ r_2cycle │
│ rt         ┆ ---     ┆ sec        ┆ n_sec     ┆   ┆ ies_out   ┆ entropy_o ┆ ncy_share ┆ ---      │
│ ---        ┆ u32     ┆ ---        ┆ ---       ┆   ┆ ---       ┆ ut        ┆ _out      ┆ i64      │
│ datetime[μ ┆         ┆ f64        ┆ f64       ┆   ┆ i64       ┆ ---       ┆ ---       ┆          │
│ s]         ┆         ┆            ┆           ┆   ┆           ┆ f64       ┆ f64       ┆          │
╞════════════╪═════════╪════════════╪═══════════╪═══╪═══════════╪═══════════╪═══════════╪══════════╡
│ 2022-09-01 ┆ 1863431 ┆ 21120.0    ┆ 1.0993e9  ┆ … ┆ 1         ┆ -1.0001e- ┆ 1.0       ┆ 0        │
│ 00:00:00   ┆         ┆            ┆           ┆   ┆           ┆ 12        ┆           ┆          │
│ 2022-09-01 ┆ 1150128 ┆ 12150.0    ┆ 6.216026e ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0        │
│ 00:00:00   ┆         ┆            ┆ 8         ┆   ┆           ┆           ┆           ┆          │
│ 2022-09-07 ┆ 516338  ┆ null       ┆ null      ┆ … ┆ 1         ┆ -9.9964e- ┆ 1.0       ┆ 0        │
│ 00:00:00   ┆         ┆            ┆           ┆   ┆           ┆ 13        ┆           ┆          │
│ 2022-09-05 ┆ 1726037 ┆ 18444.0    ┆ 1.6380e9  ┆ … ┆ 0         ┆ 0.0       ┆ 0.0       ┆ 0        │
│ 00:00:00   ┆         ┆            ┆           ┆   ┆           ┆           ┆           ┆          │
│ 2022-09-15 ┆ 998716  ┆ 35560.0    ┆ 3.7362e9  ┆ … ┆ 1         ┆ -9.9987e- ┆ 1.0       ┆ 0        │
│ 00:00:00   ┆         ┆            ┆           ┆   ┆           ┆ 13        ┆           ┆          │
│ …          ┆ …       ┆ …          ┆ …         ┆ … ┆ …         ┆ …         ┆ …         ┆ …        │
│ 2022-09-01 ┆ 1725707 ┆ 32760.0    ┆ null      ┆ … ┆ 1         ┆ -1.0001e- ┆ 1.0       ┆ 0        │
│ 00:00:00   ┆         ┆            ┆           ┆   ┆           ┆ 12        ┆           ┆          │
│ 2022-09-15 ┆ 381566  ┆ null       ┆ null      ┆ … ┆ 1         ┆ -9.8965e- ┆ 1.0       ┆ 0        │
│ 00:00:00   ┆         ┆            ┆           ┆   ┆           ┆ 13        ┆           ┆          │
│ 2022-09-11 ┆ 987511  ┆ 44260.0    ┆ 5.5007e9  ┆ … ┆ 1         ┆ -1.0001e- ┆ 1.0       ┆ 0        │
│ 00:00:00   ┆         ┆            ┆           ┆   ┆           ┆ 12        ┆           ┆          │
│ 2022-09-15 ┆ 612834  ┆ null       ┆ null      ┆ … ┆ 1         ┆ -9.9987e- ┆ 1.0       ┆ 0        │
│ 00:00:00   ┆         ┆            ┆           ┆   ┆           ┆ 13        ┆           ┆          │
│ 2022-09-09 ┆ 1507040 ┆ null       ┆ null      ┆ … ┆ 1         ┆ -1.0001e- ┆ 1.0       ┆ 0        │
│ 00:00:00   ┆         ┆            ┆           ┆   ┆           ┆ 12        ┆           ┆          │
└────────────┴─────────┴────────────┴───────────┴───┴───────────┴───────────┴───────────┴──────────┘

# Write

In [59]:
final.write_csv('../data/HI-Medium_SSL.csv')